**`Tutorial Tensorflow Basic`**


   <center>  <img src=https://devclass.com/wp-content/uploads/2018/08/Tensorflow.jpg width="800">  </center> 




In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
  print(tf.__version__)
except Exception:
  pass

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

Define a constant

In [0]:
x = tf.constant(10)

In [4]:
print(x)
print(type(x))

tf.Tensor(10, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [0]:
x1 = tf.constant(10)
x2 = tf.constant(30)
x_sum = x1+x2

In [6]:
print(x1)
print(x2)
print(x_sum)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(40, shape=(), dtype=int32)


In [0]:
u = tf.constant([3,4,3])
v = tf.constant([1,4,3])
z = tf.add(u,v)

In [8]:
print(u)
print(v)
print(z)

tf.Tensor([3 4 3], shape=(3,), dtype=int32)
tf.Tensor([1 4 3], shape=(3,), dtype=int32)
tf.Tensor([4 8 6], shape=(3,), dtype=int32)


Define a variable

In [0]:
y = tf.Variable([1,4])

In [10]:
y

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 4], dtype=int32)>

Define a function

In [0]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x**2,3)+y**2)

In [0]:
f2 = tf.function(f1)

Gradient

In [0]:
# define a function y=ax+b --> y = 2x-3

X = tf.Variable(30.0) #random initailization
A = tf.constant(22.0)
B = tf.constant(1.0)

In [0]:
y = A * X - B

In [0]:
def gradient():
  with tf.GradientTape() as tape:
    loss = A * X - B
    dX = tape.gradient(loss,X)
  return dX

In [16]:
gradient()

<tf.Tensor: shape=(), dtype=float32, numpy=22.0>

Perceptron

In [0]:
import numpy as np

In [0]:
class Neuron(object):
  def __init__(self, num_inputs, activation_fn):
    super().__init__()

    self.W = np.random.rand(num_inputs)
    self.b = np.random.rand(1)
    self.activation_fn = activation_fn

  def forward(self,x):
    z = np.dot(x, self.W) + self.b
    return self.activation_fn(z)

In [0]:
np.random.seed(42)
x = np.random.rand(3).reshape(1,3)

In [20]:
x

array([[0.37454012, 0.95071431, 0.73199394]])

In [0]:
y_ = lambda y:0 if y<=0 else 1

In [0]:
perceptron = Neuron(num_inputs=x.size, activation_fn = y_)

In [23]:
print(perceptron.W)
print(perceptron.b)

[0.59865848 0.15601864 0.15599452]
[0.05808361]


In [24]:
perceptron.forward(x)

1

FullyConnectedLayer


In [0]:
class FullyConnectedLayer(object):
  def __init__(self, num_inputs, layer_size,activation_fn):
    super().__init__()

    self.layer_size = layer_size
    self.W = np.random.standard_normal((num_inputs, layer_size))
    self.b = np.random.standard_normal(layer_size)
    self.activation_fn = activation_fn
    

  def forward(self,x):
    z = np.dot(x, self.W) + self.b
    return self.activation_fn(z)

In [0]:
x1 = np.random.uniform(-1,1,2).reshape(1,2)
relu_fn = lambda y:np.maximum(y,0)

In [27]:
print(x1)
print(x1.shape)

[[0.73235229 0.20223002]]
(1, 2)


In [0]:
FullyConnected = FullyConnectedLayer(2,3, relu_fn)

In [29]:
FullyConnected.forward(x1)

array([[0.20416035, 0.        , 0.        ]])